# Generated by Django 3.0.7 on 2020-06-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParraWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea_n',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
