# Generated by Django 3.0.7 on 2020-06-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParraWebApp', '0003_auto_20200627_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea_n',
            old_name='fechalimite',
            new_name='fecha_limite',
        ),
    ]
