# Generated by Django 3.0.7 on 2020-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParraWebApp', '0004_auto_20200627_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea_n',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='tarea_n',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Fecha limite'),
        ),
    ]
